#!/data/data/com.termux/files/usr/bin/bash
# push - combined local + remote
git add *
if ! git diff --cached --quiet; then git commit -m "$1"; else echo "⚠️ Nothing to commit"; fi
git pull --rebase origin main || echo "⚠️ Conflicts handled"
git push origin main
